config/routes.rb
Rails.application.routes.draw do

  root 'suggestions#index'

  resources :suggestions do
    member do
      post 'endorse', :defaults => { :format => 'json' }
    end
    collection do
      get :autocomplete_tag_name
    end
  end

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_readonly :name, :description, :suggestion_id
  acts_as_taggable

  #Time in seconds when the user can destroy the record after creating
  EPHEMERAL_LIFE = 60

  def is_ephemeral?
    (Time.now - self.created_at).to_i < EPHEMERAL_LIFE
  end

  def ephemeral_life_remaining
    [EPHEMERAL_LIFE - (Time.now - self.created_at).to_i, 0].max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.order(sort_column + " desc")

    if params[:tag]
      @suggestions = @suggestions.tagged_with(params[:tag])
    end

    @suggestions
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params_new)

    respond_to do |format|
      if @suggestion.save
        cookies[@suggestion.id] = "true"
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.'\
          ' You will have a limited time to delete the suggestion.' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params_update)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /suggestions/1/endorse.json
  def endorse
    @suggestion = Suggestion.find(params[:id]);
    @suggestion.score += 1

    respond_to do |format|
      if @suggestion.save
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end

    end
  end

  # # DELETE /suggestions/1
  # # DELETE /suggestions/1.json
  def destroy
    if @suggestion.is_ephemeral?
      @suggestion.destroy
      respond_to do |format|
        format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @suggestion, notice: 'Suggestion could not be deleted. Lifetime of suggestion has been over 60 seconds.' }
        format.json { render :show, status: :created, location: @suggestion }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params_new
      params.require(:suggestion).permit(:suggestion_id, :name, :description, :tag_list)
    end

    def suggestion_params_update
      params.require(:suggestion).permit(:tag_list)
    end

    def sort_column
      Suggestion.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    style = column == sort_column ? "font-weight:bold" : nil
    link_to title, {:sort => column, :tag => params[:tag]}, {:style => style}
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">

<%= yield %>
</div>

</body>
</html>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if create == "true" %>
    <div class="form-group">
      <%= f.label :name, "Title*" %><br>
      <%= f.text_field :name, :class=>"form-control", :required => true %>
    </div>
  <%end%>
  <div class="form-group">
    <%= f.label :tag_list, "Tags*" %> (ex. social, engineering, benefits)<br>
    <%= f.autocomplete_field :tag_list, autocomplete_tag_name_suggestions_path, :"data-delimiter" => ', ', :class=> "form-control", :required => true %>
  </div>
  <% if create == "true" %>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class=>"form-control" %>
    </div>
  <%end%>

  <p>* - required fields</p>

  <button type="submit" class="btn btn-default">
    <% if create == "true"%>
      Create
    <% else %>
      Edit
    <% end %>
    Suggestion
  </button>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render :partial => 'form', :locals => { :create => 'false' }  %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Suggestion Box</h1>
<%= link_to 'Add a Suggestion', new_suggestion_path %>

<div id="suggestions">
  <span class="small"> Sort By: <%= sortable "updated_at", "Updated" %> | <%= sortable "created_at", "Created" %> | <%= sortable "score", "Endorsements" %> </span>
  <% if params[:tag] %>
    <span class="pull-right small"><%= link_to "Click to remove tag filter", {:sort => params[:sort]} %></span>
  <% end %>
  <% @suggestions.each do |suggestion| %>
    <div class="row suggestion">
      <div class="col-md-1">
        <span class="score">
          <%= suggestion.score %>
        </span>
        <p class="x-small">
          Endorsements
        </p>
      </div>
      <div class="col-md-11">
        <%= link_to "", edit_suggestion_path(suggestion[:id]), :class => "edit-tags pull-right glyphicon glyphicon-pencil hidden" %>
        <h4>
          <%= suggestion.name %>
          <button type="button" class="btn btn-default btn-xs endorse" data-id=<%= suggestion.id %>>
            <span class="glyphicon glyphicon-star"></span> Endorse
          </button>
        </h4>

        <p><%= suggestion.description %></p>
        <% suggestion.tags.each do |tag| %>
          <span class="tag label pull-right"> <%= link_to tag, {:sort => params[:sort], :tag => tag.to_s} %></span>
        <% end %>
        <span class="x-small"><i>Last updated on <%= suggestion.updated_at.to_formatted_s(:long) %></i></p>
      </div>
    </div>
  <% end %>
</div>
<%= javascript_tag do %>
  $(document).ready(function() {
    $("button.endorse").each(function(idx, el) {
      if ($.cookie(String($(el).data('id'))) === "true") {
        $(el).addClass('disabled');
        $(el).html($(el).html().replace("Endorse", "Endorsed!"));
      }
    });

    $("div.suggestion").mouseover(function(e) {
      $(e.currentTarget).find(".edit-tags").removeClass("hidden");
    }).mouseout(function(e) {
      $(e.currentTarget).find(".edit-tags").addClass("hidden");
    });

    $("button.endorse").click(function(evt) {
      $.ajax({
        url: "suggestions/" + $(evt.currentTarget).data('id') + "/endorse",
        type: "POST",
        dataType: "json",
        success: function(data) {
          var $endorseBtn = $(evt.currentTarget);

          $endorseBtn.closest('.suggestion').find('.score').html(data.score);

          $.cookie($(evt.currentTarget).data('id'), true);

          $endorseBtn.html($endorseBtn.html().replace("Endorse", "Endorsed!"));
          $endorseBtn.addClass('disabled');

        }
      });
    });
  });
<% end %>

app/views/suggestions/new.html.erb
<h1>New suggestion</h1>
<%= render :partial => 'form', :locals => { :create => 'true' }  %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @suggestion.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @suggestion.tag_list %>
</p>

<p>
  <strong>Description:</strong>
  <%= @suggestion.description %>
</p>

<% if @suggestion.is_ephemeral? %>
  <%= link_to 'Delete (' + @suggestion.ephemeral_life_remaining.to_s + ')', suggestion_path(@suggestion[:id]), :method => :delete %>
<% end %>
<%= link_to 'Back', suggestions_path %>

<%= javascript_tag do %>
  $(document).ready(function() {
    var i = <%= @suggestion.ephemeral_life_remaining %>,
      interval = setInterval(function() {
        i--;
        $('a[data-method="delete"]').html("Delete (" + i + ")")
      },1000);

    setTimeout(function( ) {
      clearInterval(interval);
      $('a[data-method="delete"]').hide();
    }, <%= @suggestion.ephemeral_life_remaining %>000);

  });
<% end %>